// Dialogs.properties',
// Contains the Spanish options of all the elements of the dialogs',
// Posible labels for the buttons of the dialogs',
export const dialog = {
Yeslabel : 'Si',
Nolabel : 'No',
Cancellabel : 'Cancelar',
Ignorelabel : 'Ignorar',
Modifylabel : 'Modificar',
OKlabel : 'Aceptar',
Applylabel : 'Aplicar',
Constraintslabel : 'Restricciones',
// Labels of the About dialog',
AboutTitlelabel : 'Sobre Elvira',
AboutTextlabel : 'Proyecto Elvira',
// Labels of the Quit Dialog',
QuitTitlelabel : 'Elvira - Salir',
QuitTextlabel : '�Desea salir de Elvira?',
// Labels of the Unsaved Dialog',
UnsavedTitlelabel : 'Elvira - Cambios no guardados',
UnsavedTextlabel1 : 'La red',
UnsavedTextlabel2 : 'ha sido modificada �Desea guardar los cambios?',
// Labels of the empty state warning message',
EmptyStateTitlelabel : 'Elvira - Aviso',
EmptyStateTextlabel : 'La tabla de estados contiene casillas vacias',
// Labels for the EditIDiagramConstrains dialog',
EditConstraintslabel : 'Editar Restricciones para:',
EditConstraintsNewlabel : 'Nueva',
EditConstraintsEditlabel : 'Editar',
EditConstraintsDeletelabel : 'Borrar',
EditConstraintsconstraintsTypeDialogTitlelabel : 'Tipo de Restricci�n',
EditConstraintsNoSenseStatelabel : 'Estado sin Sentido',
EditConstraintsGenerallabel : 'General',
EditConstraintsstatesDialogTitlelabel : 'Elegir estado',
// Labels for the EditNonSenseConstraints dialog',
ENSCTitlelabel : 'Crear Restricci�n de "Variable carece de sentido"',
ENSCDecisionlabel : 'Nodos Decisi�n',
ENSCChancelabel : 'Nodos Aleatorios',
// Labels of the EditVariable dialog',
EditVariableNamelabel : 'Nombre',
EditVariableTitlelabel : 'T�tulo',
EditVariableCommentlabel : 'Comentario',
EditVariableKindlabel : 'Clase de Nodo',
EditVariableClasslabel : 'Función',
EditVariableUnitslabel : 'Unidades',
EditVariableChancelabel : 'Nodo Aleatorio',
EditVariableDecisionlabel : 'Nodo Decision',
EditVariableUtilityNodelabel : 'Nodo Utilidad',
EditVariableUtilitylabel : 'Utilidad',
EditVariableTypelabel : 'Tipo de variable',
EditVariableDiscretelabel : 'Discreta',
EditVariableContinuouslabel : 'Continua',
EditVariableHybridlabel : 'H�brida',
EditVariableRelevancelabel : 'Relevancia',
EditVariableValuesTypelabel : 'Tipo de valores',
EditVariableAddStatelabel : 'A�adir Nuevo Estado',
EditVariableRemoveStatelabel : 'Borrar Estado',
EditVariableStatelabel : 'Estado',
EditVariableValueslabel1 : 'Presente - Ausente',
EditVariableValueslabel2 : 'Si - No',
EditVariableValueslabel3 : 'Positivo - Negativo',
EditVariableValueslabel4 : 'Leve - Severo',
EditVariableValueslabel5 : 'Alto - Medio - Bajo',
EditVariableValueslabel6 : 'Otro',
EditVariableProbabilisticlabel : 'Probabilista',
EditVariableDeterministiclabel : 'Determinista',
EditVariableOptimallabel : '�ptima',
EditVariableAllParlabel : 'Todos los par�metros',
EditVariableIndParlabel : 'Par�metros independientes',
EditVariableValueslabel : 'Valores',
EditVariableProbabilitieslabel : 'Probabilidades',
EditVariableCPTlabel : 'TPC',
EditVariableCanParlabel : 'Par�metros can�nicos',
EditVariableDiezlabel : 'Netos',
EditVariableHenrionlabel : 'Compuestos',
EditVariableRelationTypelabel : 'Tipo de relaci�n',
EditVariableNodelabel : 'Nodo',
EditVariableRelationlabel : 'Relaci�n',
EditVariablePolicylabel : 'Pol�tica',
EditVariableParentsTypelabel : 'Tipo de Padre',
EditVariableParentslabel : 'Padres',
EditVariableAddParentlabel : 'A�adir Padre',
EditVariableRemoveParentlabel : 'Borrar Padre',
EditVariableAddFromGUIlabel : 'Seleccionar Padres',
EditVariablereturnDialoglabel : 'Di�logo de retorno',
EditVariablereturnButtonlabel : 'Pulsar al terminar',
EditVariableGenerallabel : 'General',
EditVariableORlabel : 'OR',
EditVariableMAXlabel : 'MAX',
EditVariableInhibitorslabel : 'AND (s�lo inhibidores)',
EditVariableSubstitutorslabel : 'AND (inhibidores/sustitutos)',
EditVariableXORlabel : 'XOR',
//A�adido para la edici�n de �rboles de probabilidad',
EditVariableProbabilityTreelabel : 'Arbol Prob',
EditVariableNewDecisionlabel : 'A�adir Nueva Decisi�n',
EditVariableDeleteDecisionlabel : 'Borrar Decisi�n',
EditVariableLeakylabel : 'Residual',
EditVariablerelationDialogTitlelabel : 'Tipo de Relaci�n',
EditVariablerelationDialogGenerallabel : 'General',
EditVariablerelationDialogOrlabel : 'Or',
EditVariablerelationDialogCausalMaxlabel : 'Max Causal',
EditVariablerelationDialogGeneralizedMaxlabel : 'Max Generalizada',
EditVariablerelationDialogAndlabel : 'And',
EditVariablerelationDialogMinlabel : 'Min',
EditVariablerelationDialogXorlabel : 'Xor',
EditVariablerelationDialogOptimalPolicylabel : 'Pol�tica �ptima',
EditVariablerelationDialogForcePolicylabel : 'Forzar pol�tica',
EditVariableparentsDialogTitlelabel : 'Elegir Padres',
//A�adido para la edici�n de �rboles de probabilidad',
EditVariablerelationDialogProbabilityTreelabel : 'Arbol Prob',
ConditionalTableTitlelabel : 'Nodo',
ConditionalTableprobabilitieslabel : 'Distribuci�n a posteriori',
ConditionalTableutilitieslabel : 'Utilidades',
    // Names of the states',
    Statespresent : 'presente',
    Statesabsent : 'ausente',
    Statesyes : 'si',
    Statesno : 'no',
    Statespositive : 'positivo',
    Statesnegative : 'negativo',
    Stateshigh : 'alto',
    Statesmedium : 'medio',
    Stateslow : 'bajo',
    Statessevere : 'severo',
    Statesmoderate : 'moderado',
    Statesmild : 'leve',
// Labels of the FSEditFunction dialog',
FSEditFunctionParentslabel : 'Padres:',
FSEditFunctionIndex_of_Distributionslabel : 'Indice de las distribuciones extremas',
FSEditFunctionClose_Windowlabel : 'Cerrar Ventana',
FSEditFunctionEdit_Nodelabel : 'Editar Nodo',
// Labels of the QuitEditor dialog',
QuitEditorFirstMessagelabel : '�Desea guardar los cambios efectuados en',
QuitEditorSecondMessagelabel : '?',
QuitEditorYeslabel : 'Si',
QuitEditorNolabel : 'No',
QuitEditorCancellabel : 'Cancelar',
// Labels of New dialog',
NewDialogKindlabel : 'Elija el tipo de la red a crear',
NewDialogOklabel : 'Aceptar',
NewDialogCancellabel : 'Cancelar',
NewDialogBayesian_Networklabel : 'Red Bayesiana',
NewDialogInfluence_Diagramlabel : 'Diagrama de Influencia',
NewDialogDecision_Analysis_Networklabel : 'Red de An�lisis de Decisiones',
NewDialogMarkov_Networklabel : 'Red de Markov',
// Labels for the Open URL Dialog',
OpenURLTitlelabel : 'Elvira - Abrir URL',
OpenURLOklabel : 'Ok',
OpenURLCancellabel : 'Cancelar',
// String used to call the files without name',
NewDialogUntitledlabel : 'Sin_titulo',
// Case Monitor options',
CaseMonitoraddtip : 'A�adir caso',
CaseMonitoraddmnemonic : 'A',
CaseMonitordeletetip : 'Borrar caso',
CaseMonitordeletemnemonic : 'B',
CaseMonitoredittip : 'Editar caso',
CaseMonitoreditmnemonic : 'E',
CaseMonitoroptionstip : 'Opciones',
CaseMonitoroptionsmnemonic : 'O',
CaseMonitorhelptip : 'Ayuda',
CaseMonitorhelpmnemonic : 'Y',
// NetworkPropertiesDialog options',
NetPropertiesTitlelabel : 'Propiedades de la red',
NetPropertiesNetTypelabel : 'Tipo de red',
NetPropertiesVarTypelabel : 'Tipo de variables',
NetPropertiesBnetlabel : 'Red Bayesiana',
NetPropertiesMnetlabel : 'Red de Markov',
NetPropertiesIDiagramlabel : 'Diagrama de Influencia',
NetPropertiesChainlabel : 'Chain Graph',
NetPropertiesDanlabel : 'Red de An�lisis de Decisiones',
NetPropertiesDiscretelabel : 'Discreta',
NetPropertiesContinuouslabel : 'Continua',
NetPropertiesBothlabel : 'Ambas',
NetPropertiesNamelabel : 'Nombre de la red',
NetPropertiesNetTitlelabel : 'T�tulo',
NetPropertiesAuthorlabel : 'Autor',
NetPropertiesCommentlabel : 'Comentarios',
NetPropertiesLastlabel : '��ltima modificaci�n',
NetPropertiesChangedlabel : 'Modificada por',
NetPropertiesVersionlabel : 'Versi�n',
NetPropertiesDefinitionlabel : 'Definici�n',
NetPropertiesInfolabel : 'Info',
// LinkPropertiesDialog options',
LinkPropertiesTitlelabel : 'Propiedades del enlace',
LinkPropertiesDirectedlabel : 'Dirigido',
LinkPropertiesUndirectedlabel : 'No dirigido',
LinkPropertiesParentlabel : 'Origen',
LinkPropertiesChildlabel : 'Destino',
// ProgressDialog labels',
ProgressDialogLoading : 'Cargando',
ProgressDialogVersion : 'Versi�n',
ProgressDialogFrame : 'Ventana Principal',
ProgressDialogImages : 'Im�genes',
ProgressDialogPanes : 'Paneles',
ProgressDialogToolbars : 'Barras de herramientas',
ProgressDialogMenus : 'Men�s',
ProgressDialogMessageWindow : 'Ventana de mensajes',
ProgressDialogListeners : 'Eventos',
// FusionDialog labels',
FusionDialogChoose : 'Elija dos redes',
FusionDialogQualitative : 'Tipo cuantitativo',
FusionDialogQuantitative : 'Tipo cualitativo',
FusionDialogFusion : 'Fusi�n',
FusionDialogUnion : 'Uni�n',
FusionDialogIntersection : 'Intersecci�n',
FusionDialogExtended : 'Intersecci�n Extendida',
FusionDialogMaximal : 'Maximal',
FusionDialogLinear : 'Linear pool',
FusionDialogLog : 'Logaritmic pool',
FusionDialogNoisyOR : 'Noisy OR',
FusionDialogNoisyORLoose : 'Noisy OR with loose probability',
FusionDialogTitle : 'Opciones de fusi�n',
// OptionsInferece Dialog labels',
OpInferenceDialogTitle : 'Opciones de inferencia',
OpInferenceDialogMaxStored : 'N�mero m�ximo de casos guardados',
OpInferenceDialogAutomatic : 'Autom�tico',
OpInferenceDialogOnDemand : 'Manual',
OpInferenceDialogPosteriori : 'Probabilidad a posteriori',
OpInferenceDialogMostProbable : 'Explicaci�n m�s probable',
OpInferenceDialogKMostProbable : 'K explicaciones m�s probables',
OpInferenceDialogTotal : 'Total',
OpInferenceDialogPartial : 'Parcial',
OpInferenceDialogVariables : 'Seleccionar variables',
OpInferenceDialogPropagation : 'Propagaci�n',
OpInferenceDialogAbduction : 'Abducci�n',
OpInferenceDialogObjetive : 'Objetivo de la inferencia',
// PurposeDialog labels',
PurposeDialogTitle : 'Selecci�n de los nodos a expandir por su funci�n',
Rollabel: 'Usar Rol',
Roltip: 'Seleccionar por el rol',
Oklabel: 'Aceptar',
Cancellabel : 'Cancelar',
Treatment: 'Tratamiento',
Riskfactor: 'Factor de riesgo',
Symptom: 'S�ntoma',
Sign: 'Signo',
Disease: 'Enfermedad/Anomal�a',
Test: 'Prueba',
Aux: 'Auxiliar',
Other: 'Otro',
Defined: 'Definir nuevo',
New: 'Nueva',
// Case identifiers',
PriorProb : 'Probabilidades a priori',
CaseNum : 'Caso n�mero',
// ExplainCase labels',
State: 'Estado',
PriorAcum: 'Prior Acum.',
PosteriorAcum: 'Posterior Acum.',
AcumRatio: 'Acum Ratio',
Variable: 'Variable',
Value: 'Valor',
ExplainingCase : 'Explicaci�n de un Caso',
Identifier : 'Identificador',
Evidence : 'Evidencia',
ProbabilityEvidence : 'Probabilidad de la evidencia',
Name : 'Nombre',
Why : '�Por qu�?',
How : '�C�mo?',
Close : 'Cerrar',
Hypothesis : 'Hip�tesis',
//Options Explanation labels',
Explanation : 'Explicaci�n',
Comparation : 'Comparaci�n',
Variation : 'Variaci�n',
OptionsExpl : 'Opciones para la explicaci�n',
Automatic : 'Autom�tica',
Nonauto : 'Manual',
CasePrior : 'Caso Inicial (Probabilidades a priori)',
CaseBefore : 'Caso anterior',
Absolute : 'Absoluta',
Relative : 'Relativa',
Threshold : 'Umbral',
NoOption : 'Error. Esta opci�n no puede seleccionarse',
UnExCase : 'Error. El caso seleccionado no existe',
ValidCase : 'Caso v�lido',
//FindingDialog labels',
SetEvidence : 'Introducir hallazgo',
valuesTip : 'Pulsa para ver los estados del nodo',
//// DataBaseMonitor labels',
DataBaseMonitorTitle: 'Abrir fichero de casos',
DataBaseMonitormLearningtab: 'Aprendizaje autom�tico',
DatabaseMonitorPreprocesstab: 'Opciones de preproceso',
DatabaseMonitorProcess: 'Procesar',
DataBaseMonitorBrowselabel: 'Seleccionar',
DataBaseMonitorCaseLabellabel: 'Fichero de casos :',
DataBaseMonitorFileChoosertitle: 'Abrir fichero .dbc',
DataBaseMonitorCancellabel: 'Cancelar',
DataBaseMonitorSupervisedtab: 'Clasificaci�n supervisada',
DataBaseMonitorUnsupervisedtab: 'Clasificaci�n no supervisada',
DataBaseMonitorFactorizationtab: 'Factorizaci�n',
DataBaseMonitorJointProblabel: 'Factorizaci�n de la distribuci�n de probabilidad conjunta',
DataBaseMonitorDiscretizationlabel: 'Discretizaci�n de variables',
DataBaseMonitorImputationlabel: 'Imputaci�n de valores perdidos',
DataBaseMonitorFiltertab: 'Medidas filter',
DataBaseMonitorPostLearningtab: 'Post aprendizaje',
DataBaseMonitorPostLearningtesttab: 'Testear un clasificador',
DataBaseMonitorPostLearningcategorizetab: 'Categorizar casos',
DataBaseMonitorImputationmainlabel: 'ALGORITMO IMPUTACI�N',
DataBaseMonitorImputationclassVar: 'Variable clase',
DataBaseMonitorImputationtreeBuild: 'M�todo de construcci�n',
DataBaseMonitorImputationnoIterations: 'No. Iteraciones',
DataBaseMonitorImputationerrorClassVar: 'La variable clase debe ser superior a 0',
DataBaseMonitorImputationerrorNoIterations: 'El n�mero de iteraciones debe ser superior a 0',
DataBaseMonitorImputationZerosExplanation: 'Este m�todo sustituye los valores perdidos/desconocidos con ceros. No necesita par�metros.',
DataBaseMonitorImputationAverageExplanation: 'Este m�todo sustituye los valores perdidos/desconocidos con la media de cada variable. No necesita par�metros.',
DataBaseMonitorImputationClassNodeExplanation: 'Este m�todo sustituye los valores perdidos/desconocidos con la media de los valores de una variable condicionada a la clase. Es necesario indicar la variable clase; s�lo ser� �til en clasificaci�n supervisada.',
DataBaseMonitorImputationTreeExplanation: 'Este m�todo sustituye los valores perdidos/desconocidos con valores que son calculados usando un ��rbol de Clasificaci�n. Se debe escoger el m�todo a usar de los siguientes: C4.5+ErrorBasedPrunning, ID3+ReducedErrorPrunning, o Dirichlet+ReducedErrorPrunning.',
DataBaseMonitorImputationITER_MPEExplanation: 'Este m�todo sustituye todos los valores perdidos, para cada caso, con una de las explicaciones m�s probables, usando Abducci�n. En la primera iteraci�n, la red se aprende a partir de los casos completos, y en las siguientes, usando tambi�n los casos imputados.',
DataBaseMonitorImputationINCR_MPEExplanation: 'Este m�todo sustituye todos los valores perdidos, para cada caso, con una de las explicaciones m�s probables, usando Abducci�n. Este proceso se hace de forma incremental, seg�n el n�mero de valores perdidos que haya en el caso. Al principio, la red se aprende a partir de los casos completos, y en los siguientes pasos, usa tambi�n los casos imputados.',
DataBaseMonitorImputationok: 'Imputaci�n realizada correctamente',
DataBaseMonitorDiscretizationlabel2: 'TIPO DE DISCRETIZACI�N:',
DataBaseMonitorDiscretizationmasive: 'Masiva',
DataBaseMonitorDiscretizationnormal: 'Normal',
DataBaseMonitorDiscretizationalg: 'Algoritmo',
DataBaseMonitorDiscretizationintervals: 'No. Intervalos',
DataBaseMonitorDiscretizationoptions: 'Opciones',
DataBaseMonitorDiscretizationoutFile: 'Fichero de salida',
DataBaseMonitorDiscretizationvarType: 'Tipo',
DataBaseMonitorDiscretizationdiscretize: 'Discretizar',
DataBaseMonitorDiscretizationerrorIntervals: 'El n�mero de intervalos debe ser superior a 1',
DataBaseMonitorDiscretizationok: 'Discretizaci�n realizada correctamente',
DataBaseMonitorFilterlabel: 'MEDIDA FILTER',
DataBaseMonitorFiltersavecheckbox: 'Guardar proyecci�n',
DataBaseMonitorFiltervars: 'No de variables',
DataBaseMonitorFilterfilename: 'Nombre fichero',
DataBaseMonitorFilterresultstitle: 'Resultados medida filter',
DataBaseMonitorFilterresultsfile: 'Fichero:',
DataBaseMonitorFilterresultslabel: 'Medida filter:',
DataBaseMonitorFilterresultscases: 'N�mero de casos:',
DataBaseMonitorFilterresultsvars: 'N�mero de variables:',
DataBaseMonitorFilterresultsoutfile: 'Fichero de salida:',
DataBaseMonitorFilterresultsincludevars: 'Variables inclu�das:',
DataBaseMonitorFilterresultsvar: 'Variable',
DataBaseMonitorFilterresultsmetric: 'Medida',
DataBaseMonitorFilterautolabel: 'Autom�tico',
DataBaseMonitorFilterautotip: 'Determinaci�n de un umbral de corte dado un rankeo de variables',
DataBaseMonitorMlearningLaplace: 'Correcci�n de Laplace',
DataBaseMonitorMlearningmainLabel: 'ESTRUCTURA DEL CLASIFICADOR',
DataBaseMonitorUnsupervisedEMExplanation: 'Aprende un modelo na�ve Bayes no supervisado mediante el algoritmo EM inicializado con un modelo na�ve Bayes con par�metros tomados de forma aleatoria. \nEl modelo resultante maximiza la verosimilitud del conjunto de datos de aprendizaje aunque, por la naturaleza voraz del algoritmo EM, puede ser un m�ximo local para la funci�n de verosimilitud.',
DataBaseMonitorUnsupervisedMultiStartExplanation: 'Aprende "no. de ejecuciones" modelos na�ve Bayes no supervisados mediante el algoritmo EM inicializado con un modelo na�ve Bayes con par�metros tomados de forma aleatoria. \nEl modelo resultante es el mejor de los aprendidos. De esta forma se intenta evitar los m�ximos locales en los que pueda quedar atrapada una sola ejecuci�n del algoritmo EM.',
DataBaseMonitorUnsupervisedNoClusters: 'No. de clusters',
DataBaseMonitorUnsupervisedLearning: 'M�todo de aprendizaje',
DataBaseMonitorUnsupervisedNoExecs: 'No. de ejecuciones',
DataBaseMonitorUnsupervisederrorClusters: 'El n�mero de clusters debe ser superior a 1',
DataBaseMonitorUnsupervisederrorExecs: 'Indique el n�mero de ejecuciones',
DataBaseMonitorSupervisedNBAllExplanation: 'Se construye un modelo na�ve Bayes cl�sico con todas las variables predictoras, es decir, asume que las variables predictoras son condicionalmente independientes dada la clase.',
DataBaseMonitorSupervisedWrapperSelectiveNBExplanation: 'Implementaci�n del algoritmo propuesto por Langley y Sage (1994). Se aprende una estructura na�ve Bayes donde no todas las variables del problema est�n incluidas. La selecci�n de las variables se hace por medio de una aproximaci�n wrapper de forma voraz hacia delante.',
DataBaseMonitorSupervisedWrapperSemiNBExplanation: 'Implementaci�n del algoritmo FSSJ propuesto por Pazzani (1997). Se aprende una estructura na�ve Bayes donde no todas las variables del problema tienen que estar incluidas y algunas de ellas pueden formar super-variables.',
DataBaseMonitorSupervisedTANAllExplanation: 'Siguiendo el algoritmo propuesto por Friedman y col. 1996, construye un modelo TAN. Para ello, adapta el algoritmo de Chow&Liu utilizando la informaci�n mutua condicionada de dos variables predictoras dada la clase.',
DataBaseMonitorSupervisedKDBAllExplanation: 'Siguiendo el algoritmo propuesto por Sahami 1996 construye un modelo kDB. Un modelo kDB es similar a un TAN, donde las variables predictoras pueden tener hasta k padres adem�s de la clase. Para construirlo se utiliza un algoritmo basado en la informaci�n m�tua.',
DataBaseMonitorSupervisedsubLabel: 'Subestructura',
DataBaseMonitorSupervisedfilterLabel: 'Filtrado',
DataBaseMonitorSupervisedwrapperLabel: 'Envoltura',
DataBaseMonitorSupervisedoptionsTitle: 'Opciones',
DataBaseMonitorSupervisedNotAvailabe: 'Opci�n no disponible a�n',
DataBaseMonitorSupervisedParamKError: 'Indique el par�metro k del clasificador',
DataBaseMonitorClassifierPanelfile: 'Fichero de datos:',
DataBaseMonitorClassifierPanellog: 'Log. de la verosimilitud:',
DataBaseMonitorClassifierPanelltime: 'Tiempo de aprendizaje:',
DataBaseMonitorClassifierPanelmodel: 'Modelo:',
DataBaseMonitorClassifierPanellp: 'Correcci�n de Laplace:',
DataBaseMonitorFactorizationLPLabel: 'Bayesiana',
DataBaseMonitorFactorizationDELabel: 'M�x. verosimilitud',
DataBaseMonitorFactorizationMethodLabel: 'M�TODO DE APRENDIZAJE',
DataBaseMonitorFactorizationMetricLabel: 'M�trica',
DataBaseMonitorFactorizationEstimationLabel: 'Estimaci�n :',
DataBaseMonitorFactorizationMaxParentsLabel: 'No. m�ximo de padres',
DataBaseMonitorFactorizationMaxParentsError: 'Indique el n�mero m�ximo de padres para un nodo',
DataBaseMonitorFactorizationCasesLabel: 'No. de casos',
DataBaseMonitorFactorizationCasesError: 'Indique el n�mero de casos',
DataBaseMonitorFactorizationConfLabel: 'Confianza (%)',
DataBaseMonitorFactorizationConfError: 'Indique el nivel de confianza',
DataBaseMonitorFactorizationKnowledgeLabel: 'Restricciones',
DataBaseMonitorFactorizationProcLabel: 'No. de procesadores',
DataBaseMonitorFactorizationProcError: 'Indique el n�mero de procesadores',
DataBaseMonitorFactorizationTamLabel: 'Tama�o poblaci�n',
DataBaseMonitorFactorizationTamError: 'Indique el tama�o de la poblaci�n',
DataBaseMonitorFactorizationNoIterLabel: 'No. de iteraciones',
DataBaseMonitorFactorizationNoIterError: 'Indique el n�mero de iteraciones',
DataBaseMonitorFactorizationMaxNeigLabel: 'No. m�ximo de vecinos',
DataBaseMonitorFactorizationMaxNeigError: 'Indique el n�mero m�ximo de vecinos',
DataBaseMonitorTestSelecClassifierLabel: 'Seleccione el clasificador:',
DataBaseMonitorTestCategorizeLabel: 'Categorizaci�n de casos',
DataBaseMonitorTestTestLabel: 'Testear un clasificador',
DataBaseMonitorTestCvLabel: 'Validaci�n cruzada',
DataBaseMonitorTestkParameterLabel: 'Par�metro k',
DataBaseMonitorTesterrorK: 'Indique el par�metro k de la validaci�n',
DataBaseMonitorTestnoClassError: 'Seleccione un modelo supervisado',
DataBaseMonitorTestnoLearnt: 'Debe aprender un modelo primero',
DataBaseMonitorTestresultstitle: 'Resultados de la validaci�n cruzada',
DataBaseMonitorTestresultsclassif: 'Clasificador:',
DataBaseMonitorTestresultsacc: 'Precisi�n:',
DataBaseMonitorTestresultsmatrix: 'Matriz de confusi�n media',
DataBaseMonitorNoDBCtext: 'Debe seleccionar un fichero de casos',
DataBaseMonitorNoOutDBCtext: 'Debe seleccionar un fichero de casos de salida',
////',
//// ConstraintKnowledgeDialog labels',
ConstraintKnowledgeDialogExistencetab: 'Restricciones de Existencia',
ConstraintKnowledgeDialogExistencelabelTitle: 'RESTRICCIONES DE EXISTENCIA',
ConstraintKnowledgeDialogAbsencetab: 'Restricciones de Ausencia',
ConstraintKnowledgeDialogAbsencelabelTitle: 'RESTRICCIONES DE AUSENCIA',
ConstraintKnowledgeDialogPartialOrdertab: 'Restricciones de Orden Parcial',
ConstraintKnowledgeDialogPartialOrderlabelTitle: 'RESTRICCIONES DE ORDEN PARCIAL',
ConstraintKnowledgeDialoglabelTail: 'Nodo Origen',
ConstraintKnowledgeDialoglabelHead: 'Nodo Destino',
ConstraintKnowledgeDialoglabelSelected: 'Enlaces/aristas seleccionados',
ConstraintKnowledgeDialogPartialOrderlabelSelected: 'Enlaces seleccionados',
ConstraintKnowledgeDialoglabelDirected: 'Dirigido',
ConstraintKnowledgeDialoglabelInput: 'Fichero de entrada',
ConstraintKnowledgeDialoglabelOutput: 'Fichero de salida',
ConstraintKnowledgeDialoglabelAdd: 'A�adir -->',
ConstraintKnowledgeDialoglabelQuit: '<-- Quitar',
ConstraintKnowledgeDialoglabelAccept: 'Aceptar',
ConstraintKnowledgeDialoglabelCancel: 'Cancelar',
ConstraintKnowledgeDialogtitleBorder: 'Leer/Guardar restricciones',
ConstraintKnowledgeDialogbuttonSelecInput: 'Seleccionar',
ConstraintKnowledgeDialogbuttonSelecOutput: 'Seleccionar',
ConstraintKnowledgeDialogErrorAddmsg: 'ERROR: No se puede a�adir la restricci�n.',
ConstraintKnowledgeDialogErrorAddconsistent: 'No es consistente con las restricciones almacenadas.',
ConstraintKnowledgeDialogquitAction1: '�Realmente quieres borrar los siguientes enlaces:\n',
ConstraintKnowledgeDialogExistencequitAction2: 'de las restricciones de Existencia?',
ConstraintKnowledgeDialogAbsencequitAction2: 'de las restricciones de Ausencia?',
ConstraintKnowledgeDialogPartialOrderquitAction2: 'de las restricciones de Orden Parcial?',
ConstraintKnowledgeDialogExistenceErrorQuitmsg: 'ERROR: No se puede eliminar la restricci�n de existencia:',
ConstraintKnowledgeDialogExistenceErrorSavemsg: 'ERROR: No se pudieron guardar las restricciones de existencia',
ConstraintKnowledgeDialogAbsenceErrorQuitmsg: 'ERROR: No se puede eliminar la restricci�n de ausencia:',
ConstraintKnowledgeDialogAbsenceErrorSavemsg: 'ERROR: No se pudieron guardar las restricciones de ausencia',
ConstraintKnowledgeDialogPartialOrderErrorQuitmsg: 'ERROR: No se puede eliminar la restricci�n de orden parcial:',
ConstraintKnowledgeDialogPartialOrderErrorSavemsg: 'ERROR: No se pudieron guardar las restricciones de orden parcial',
ConstraintKnowledgeDialogExistenceErrorReadmsg1: 'ERROR: Problema al leer el fichero de restricciones de existencia.',
ConstraintKnowledgeDialogExistenceErrorReadmsg2: 'ERROR: Problema al leer las restricciones de existencia desde el fichero.',
ConstraintKnowledgeDialogAbsenceErrorReadmsg1: 'ERROR: Problema al leer el fichero de restricciones de ausencia.',
ConstraintKnowledgeDialogAbsenceErrorReadmsg2: 'ERROR: Problema al leer las restricciones de ausencia desde el fichero.',
ConstraintKnowledgeDialogPartialOrderErrorReadmsg1: 'ERROR: Problema al leer el fichero de restricciones de orden parcial.',
ConstraintKnowledgeDialogPartialOrderErrorReadmsg2: 'ERROR: Problema al leer las restricciones de orden parcial desde el fichero.',
ConstraintKnowledgeDialogErrorReadmsg3: 'ATENCI�N: No se ha a�adido ninguna restricci�n.',
ConstraintKnowledgeDialogrepair: 'La red aprendida no verifica las restricciones almacenadas,\ndebido a que el algoritmo de aprendizaje usado no soporta\nrestricciones en el proceso de aprendizaje.\n�Se debe reparar la red para verificar las restricciones?',
////',
NetPropertiesDefaultslabel: 'Valores por defecto',
NetPropertiesDefaultStateslabel: 'Estados por defecto',
ShowDecisionUtilitylabel: 'Utilidad',
ShowDecisionDecisionlabel: 'Decisi�n',
EditVariablerelationDialogAddlabel: 'Utilidad - Suma',
//Nodo utilidad que multiplica la utilidad de sus padres',
EditVariablerelationDialogMultiplylabel: 'Utilidad - Multiplicaci�n',
EditVariableRelationUtilityAddlabel: 'Suma',
EditVariableRelationUtilityMultiplylabel: 'Multiplicaci�n',
EditVariableCValueslabel: 'Valores Continuos',
EditVariableMinCVLabellabel: 'M�nimo',
EditVariableMaxCVLabellabel: 'M�ximo',
EditVariablePrecisionCVLabellabel: 'Precisi�n',
EditVariableUndefValCVLabellabel: 'Valor de Variable Indef',
EditVariableUnitCVLabellabel: 'Unidad (String)',
EditVariableCBorderTextlabel: 'Variable Continua',
EditVariableDBorderTextlabel: 'Variable Discreta',
NetPropertiesIDWithSVNodeslabel: 'DI con Nodos Super Valor',
// Labels of Export Dialog',
ExportElviralabel: 'Exportar fichero de casos',
Exporttitle: 'Exportar fichero de casos',
ExportBrowsebutton: 'Seleccionar',
ExportDbcFilelabel: 'Fichero de casos :',
ExportDbcFileChoosertitle: 'Abrir fichero .dbc :',
ExportOutFilelabel: 'Fichero de salida :',
ExportOutFileChoosertitle: 'Seleccionar fichero .csv :',
ExportExportbutton: 'Exportar',
// Labels of Import Dialog',
Importtitle: 'Importar fichero de casos',
ImportElviralabel: 'Importar fichero de casos',
ImportCsvFilelabel: 'Fichero .csv :',
ImportDbcFilelabel: 'Fichero .dbc :',
ImportCsvFileChoosertitle: 'Abrir fichero .csv',
ImportDbcFileChoosertitle: 'Seleccionar fichero .dbc',
ImportBrowsebutton: 'Seleccionar',
ImportImportlabel: 'Importar',
ImportDBNamelabel: 'Nombre de la Base de Datos',
ImportProcessbutton: 'Procesar',
ImportNamelabel: 'Nombre :',
ImportTitlelabel: 'T�tulo :',
ImportCommentlabel: 'Comentario',
ImportNoStateslabel: 'No. Estados :',
ImportNoCaseslabel: 'No. Casos :',
ImportMaxValuelabel: 'Valor M�ximo :',
ImportMinValuelabel: 'Valor M�nimo :',
ImportSeparatorlabel: 'Separador de campos :',
ImportChooseEditVariablelabel: 'Elija la variable a editar :',
ImportForceAdviselabel: 'Algunas variables num�ricas se han considerado',
ImportForceAdviselabel2: 'discretas. Forzar continuidad :',
ImportForceAdviselabel3: 'No hay variables num�ricas no continuas.',
ImportForceAdviselabel4: 'No es necesario forzar la continuidad a ninguna.',
ImportForceMassivelabel: 'En todas',
ImportForceNormallabel: 'Estudiar variables',
ImportForceNothinglabel: 'En ninguna',
ImportStateslabel : 'Editar nombres de estados :',
ImportStatesNewNamelabel: 'Nombre nuevo :',
ImportOptionCsvlabel: 'Opciones para el fichero .csv :',
ImportOptionDbclabel: 'Opciones para el fichero .dbc :',
ImportOptionSeparatorlabel1: 'Punto y coma',
ImportOptionSeparatorlabel2: 'Coma',
ImportEditToolTiplabel : 'Hace efectivos los cambios en la variable actual',
ImportSaveChangeslabel: 'Guardar cambios',
ImportForceQuestionlabel: '�Forzar continuidad?',
ImportEditPanellabel: 'Editar Variables',
ImportOptionPanellabel: 'Opciones para los ficheros',
ImportForcePanellabel: 'Forzar Continuidad',
ImportOptionLabel4label: 'Escoja el separador y pulse "Analizar" :',
ImportEditExplanationLabellabel: '(Debe guardar cambios para cada variable)',
ImportAnalyseButtonbutton: 'Analizar',
//Introducidos para el analisis de sensibilidad',
SensitivityAnalysisTitulo : 'An�lisis de sensibilidad de',
SensitivityAnalysisModParam : 'Modificar par�metros',
SensitivityAnalysisAnalisis : 'An�lisis',
SensitivityAnalysisSelTodos : 'Sel. todos',
SensitivityAnalysisDeselTodos : 'Desel. todos',
SensitivityAnalysisDParam : 'An�lisis sobre un par�metro',
SensitivityAnalysisDTornado : 'Diagrama de tornado',
SensitivityAnalysisDSpider : 'Diagrama de ara�a',
SensitivityAnalysisDRelevancia : 'Tabla de relevancia',
SensitivityAnalysisSeleccionar : 'Seleccionar',
SensitivityAnalysisColor : 'Color',
SensitivityAnalysisNumero : 'N�mero',
SensitivityAnalysisNodo : 'Nodo',
SensitivityAnalysisParametro : 'Par�metro',
SensitivityAnalysisValor : 'Valor',
SensitivityAnalysisValorRef : 'Valor ref.',
SensitivityAnalysisMinimo : 'M�nimo',
SensitivityAnalysisMaximo : 'M�ximo',
SensitivityAnalysisApliCambios : 'Aplicar cambios',
SensitivityAnalysisNombre : 'Nombre',
SensitivityAnalysisModificado : 'El diagrama ha sido modificado con �xito',
SensitivityAnalysisEstado : 'Estado',
SensitivityAnalysisUtilidad : 'Utilidad',
SensitivityAnalysisPuntoCercano : 'Punto m�s cercano',
SensitivityAnalysisSelecUnicoParam : 'Seleccione un �nico par�metro',
SensitivityAnalysisDecision : 'Decisi�n',
SensitivityAnalysisRelevancia : 'Relevancia',
SensitivityAnalysisError : 'El diagrama no se ha cargado correctamente',
SensitivityAnalysisConfiguration : 'Configuraci�n'
}
