//# Menus_sp.properties contains the Spanish options for the menus and the toolbar',
//# Options of the file menu and items of the toolbar related with it',
export const menu ={
Filelabel:'Archivo',
Filemnemonic:'A',
FileNewlabel:'Nuevo',
FileNewshortcut:'N',
FileNewtip:'Crea una nueva red',
FileNewmnemonic:'N',
FileOpenlabel:'Abrir red ...',
FileOpenshortcut:'A',
FileOpentip:'Abre una red ya existente',
FileOpenmnemonic:'A',
FileOpenDBClabel:'Abrir fichero de casos ...',
FileOpenDBCshortcut:'F',
FileOpenDBCtip:'Opciones para el tratamiento de ficheros de casos',
FileOpenDBCmnemonic:'F',
FileImportlabel:'Importar fichero de casos ...',
FileImportmnemonic:'I',
FileExportlabel:'Exportar fichero de casos ...',
FileExportmnemonic:'E',
FileOpenURLlabel:'Abrir URL ...',
FileOpenURLmnemonic:'U',
FileSavelabel:'Guardar red',
FileSaveshortcut:'G',
FileSavetip:'Guarda la red actualmente activa',
FileSavemnemonic:'G',
FileSaveAslabel:'Guardar red como ...',
FileSaveAsmnemonic:'O',
FileSaveAlllabel:'Guardar todas las redes',
FileSaveAllmnemonic:'T',
FileImportBnetXbiflabel:'Importar red desde XBIF',
FileImportBnetXbifmnemonic:'X',
FileExportBnetXbiflabel:'Exportar red a XBIF',
FileExportBnetXbifmnemonic:'B',
FileLoadEvidencelabel:'Cargar evidencia',
FileLoadEvidencemnemonic:'V',
FileSaveEvidencelabel:'Guardar evidencia',
FileSaveEvidencemnemonic:'I',
FileCloselabel:'Cerrar',
FileCloseshortcut:'W',
FileClosemnemonic:'E',
FileExitlabel:'Salir',
FileExitmnemonic:'S',
//# Options for the edit menu',
Editlabel:'Editar',
Editmnemonic:'E',
EditUndolabel:'Deshacer',
EditUndoshortcut:'Z',
EditUndotip:'Deshace la \u00FAltima operaci\u00F3n',
EditUndomnemonic:'D',
EditRedolabel:'Repetir',
EditRedoshortcut:'Y',
EditRedotip:'Repite la \u00FAltima operaci\u00F3n realizada',
EditRedomnemonic:'R',
EditCutlabel:'Cortar',
EditCutshortcut:'X',
EditCuttip:'Corta los objetos seleccionados en el Portapapeles',
EditCutmnemonic:'T',
EditCopylabel:'Copiar',
EditCopyshortcut:'C',
EditCopytip:'Copia los objectos seleccionados en el Portapapeles',
EditCopymnemonic:'C',
EditPastelabel:'Pegar',
EditPasteshortcut:'V',
EditPastetip:'Inserta los contenidos del Portapapeles',
EditPastemnemonic:'P',
EditDeletelabel:'Borrar',
EditDeletemnemonic:'B',
EditSelectAlllabel:'Seleccionar todo',
EditSelectAllshortcut:'S',
EditSelectAllmnemonic:'S',
EditSelectlabel:'Herramienta de seleccion',
EditSelectmnemonic:'H',
EditSelecttip:'Herramienta de seleccion',
EditChancelabel:'Insertar nodo aleatorio',
EditChancetip:'A\u00F1ade nodos aleatorios en la red',
EditChancemnemonic:'A',
EditDecisionlabel:'Insertar nodo decisi\u00F3n',
EditDecisiontip:'Inserta nodos decision en la red',
EditDecisionmnemonic:'D',
EditUtilitylabel:'Insertar nodo utilidad',
EditUtilitytip:'Inserta nodos utilidad en la red',
EditUtilitymnemonic:'U',
EditLinklabel:'Insertar enlace dirigido',
EditLinktip:'Inserta enlaces dirigidos en la red',
EditLinkmnemonic:'E',
EditunLinklabel:'Insertar enlace no dirigido',
EditunLinktip:'A\u00F1ade enlaces no dirigidos en la red',
EditunLinkmnemonic:'N',
EditinfluenceLinklabel:'Influencias',
EditinfluenceLinktip:'Muestra las influencias que transmiten los enlaces',
EditinfluenceLinkmnemonic:'F',
Editlayoutlabel:'Distribuir nodos en pantalla',
Editlayouttip:'Distribuir nodos en pantalla',
EditZoomIntip:'Aumentar zoom',
EditZoomInmnemonic:'A',
EditZoomOuttip:'Disminuir zoom',
EditZoomOutmnemonic:'D',
//# Options for the view menu',
Viewlabel:'Ver',
Viewmnemonic:'V',
ViewByNamelabel:'Por Nombre',
ViewByNamemnemonic:'N',
ViewByTitlelabel:'Por T\u00EDtulo',
ViewByTitlemnemonic:'T',
//# ADDED FOR THE VIEW MENU',
ViewsetPrecisionlabel:'Precisi\u00F3n',
ViewsetPrecisionmnemonic:'P',
ViewPrec1Itemlabel:'0.1',
ViewPrec2Itemlabel:'0.01',
ViewPrec3Itemlabel:'0.001',
ViewPrec4Itemlabel:'0.0001',
ViewPrec5Itemlabel:'0.00001',
ViewPrec6Itemlabel:'0.000001',
ViewPrec7Itemlabel:'0.0000001',
ViewPrec8Itemlabel:'0.00000001',
//# Options for the tasks menu',
Taskslabel:'Tareas',
Tasksmnemonic:'T',
TasksFusionlabel:'Fusi\u00F3n',
TasksFusionmnemonic:'F',
//# Options for the options menu',
Optionslabel:'Opciones',
Optionsmnemonic:'O',
OptionsPropagationMethodlabel:'M\u00E9todo de propagaci\u00F3n',
OptionsPropagationMethodmnemonic:'P',
OptionsLearningMethodlabel:'M\u00E9todo de aprendizaje',
OptionsLearningMethodmnemonic:'A',
OptionsGenerateDBClabel:'Generar DBC',
OptionsGenerateDBCmnemonic:'G',
OptionsConstraintsKnowledgelabel:'Restricciones del conocimiento',
OptionsConstraintsKnowledgemnemonic:'C',
OptionsInferenceOptionslabel:'Opciones para la inferencia',
OptionsInferenceOptionsmnemonic:'I',
OptionsExplanationOptionslabel: 'Opciones para la explicaci\u00F3n',
OptionsInferenceOptionsmnemonic:'E',
//# Options for the window menu',
Windowlabel:'Ventana',
Windowmnemonic:'N',
WindowCascadelabel:'Organizar en cascada',
WindowCascademnemonic:'C',
WindowMinimizeAlllabel:'Minimizar todas',
WindowMinimizeAllmnemonic:'M',
WindowRestoreAlllabel:'Restaurar todas',
WindowRestoreAllmnemonic:'R',
WindowNextlabel:'Siguiente',
WindowNextshortcut:'E',
WindowNextmnemonic:'N',
WindowPreviouslabel:'Anterior',
WindowPreviousshortcut:'R',
WindowPreviousmnemonic:'A',
WindowShowlabel:'Mostrar ventana de mensajes',
WindowShowmnemonic:'O',
//# Options for the help menu',
Helplabel:'Ayuda',
Helpmnemonic:'A',
HelpAboutlabel:'Sobre...',
HelpAbouttip:'Informaci\u00F3n sobre la versi\u00F3n de Elvira',
HelpAboutmnemonic:'S',
//# Options for the working mode',
WorkingModeEditlabel:'Edici\u00F3n',
WorkingModeInferencelabel:'Inferencia',
WorkingModeLearnlabel:'Aprendizaje',
//# Options for the popup menu',
PopupNodePropertieslabel:'Editar propiedades del nodo ..',
PopupLinkPropertieslabel:'Editar propiedades del enlace ...',
PopupNetPropertieslabel:'Editar propiedades de la red ...',
PopupDeleteNodelabel:'Borrar Nodo',
PopupDeleteLinklabel:'Borrar Enlace',
PopupDeleteSelectionlabel:'Borrar Selecci\u00F3n',
PopupExplainNodelabel:'Explicar Nodo',
PopupExplainLinklabel:'Explicar Enlace',
PopupExplainNetworklabel:'Explicar Red',
PopupContractNodelabel:'Contraer Nodo',
PopupExpandNodelabel:'Expandir Nodo',
PopupNonSenseConstraintslabel:'A\u00F1adir restricci\u00F3n "Variable carece de sentido"',
PopupaddTestDecisionlabel:'A\u00F1adir decisi\u00F3n "Realizar test"',
PopupShowDecisionTableslabel:'Mostrar pol\u00EDtica \u00F3ptima para esta decisi\u00F3n',
PopupShowPosteriorDistributionsTableslabel:'Mostrar distribuci\u00F3n a posteriori',
PopupShowUtilitiesTableslabel:'Mostrar utilidades',
//# Untitled option',
Untitledlabel:'Sin titulo',
//# Message window label',
MessageWindowlabel:'Ventana de Mensajes',
//# Undo/Redo actions',
ActionaddNodelabel:'A\u00F1adir nodo',
ActionaddLinklabel:'A\u00F1adir enlace',
Actiondeletelabel:'Borrar',
Actionmovelabel:'Mover',
ActionchangeNodelabel:'Edici\u00F3n de propiedades del nodo',
ActionchangeLinklabel:'Cambiar enlace',
ActionchangeRelationlabel:'Cambiar relaci\u00F3n',
Actioncutlabel:'Cortar selecci\u00F3n',
Actionpastelabel:'Pegar selecci\u00F3n',
//# Options of the Explanation menus and toolbar's items',
Explanationlabel:'Inferencia',
Explanationmnemonic:'I',
ExplanationThresholdlabel:'UE',
ExplanationThresholdmnemonic:'U',
ExplanationPurposelabel:'Funci\u00F3n',
ExplanationPurposemnemonic:'F',
ExplanationStorelabel:'Guardar caso',
ExplanationStoretip:'Guardar el caso en la lista de casos de memoria',
ExplanationStoremnemonic:'G',
ExplanationSavelabel:'Almacenar caso',
ExplanationSavetip:'Almacenar el caso en un fichero',
ExplanationSavemnemonic:'G',
ExplanationExpandlabel:'Expandir nodo',
ExplanationExpandtip:'Expandir nodo',
ExplanationExpandmnemonic:'X',
ExplanationContractlabel:'Contraer nodo',
ExplanationContracttip:'Contrae el nodo expandido',
ExplanationContractmnemonic:'C',
ExplanationExpNodelabel:'Explicar Nodo',
ExplanationExpLinklabel:'Explicar Enlace',
ExplanationExplainlabel:'Explicar',
ExplanationExplaintip: 'Explica el caso de evidencia actual',
ExplanationExplainmnemonic:'E',
ExplanationOptionslabel:'Opciones',
ExplanationOptionstip:'Opciones',
ExplanationOptionsmnemonic:'O',
ExplanationFirstlabel:'Primer caso',
ExplanationFirsttip:'Ir al primer caso',
ExplanationFirstmnemonic:'P',
ExplanationPreviouslabel:'Caso anterior',
ExplanationPrevioustip:'Ir al caso anterior',
ExplanationPreviousmnemonic:'A',
ExplanationNextlabel:'Siguiente caso',
ExplanationNexttip:'Ir al siguiente caso',
ExplanationNextmnemonic:'S',
ExplanationLastlabel:'Ultimo caso',
ExplanationLasttip:'Ir al \u00FAltimo caso',
ExplanationLastmnemonic:'U',
ExplanationEditorlabel:'Editor de casos',
ExplanationEditortip:'Editor de casos',
ExplanationEditormnemonic:'E',
ExplanationCaselabel:'Monitor de casos',
ExplanationCasetip:'Monitor de casos',
ExplanationCasemnemonic:'M',
ExplanationDeletelabel:'Borrar evidencia',
ExplanationDeletetip:'Borra toda la evidencia del caso actual',
ExplanationDeletemnemonic:'D',
ExplanationEmptyCaseslabel:'Vaciar lista de casos',
ExplanationEmptyCasestip:'Vaciar lista de casos',
ExplanationDeletemnemonic:'V',
ExplanationPropagatelabel :'Propagar evidencia',
ExplanationPropagatetip:'Propaga la evidencia actual',
ExplanationPropagatemnemonic:'P',
ExplanationPathslabel:'Red completa',
ExplanationPathstip:' Muestra la red completa',
ExplanationPathsmnemonic:'R',
SelectVariables:'Selecci\u00F3n de variables para abducci\u00F3n parcial',
NewVar:'Nueva variable',
OKlabel:'Aceptar',
Cancellabel:'Cancelar',
Comment:'Comentario',
Value:'Valor',
NewFinding:'Nuevo hallazgo',
DeleteEvidence:'Borrar Evidencia',
Propagate:'Propagar',
NoCaseStored:'No hay ning\u00FAn caso creado. Debe introducir evidencia',
ActiveCase:'El caso actual es el \u00FAltimo creado. Es modificable.',
ExplanationDectreelabel:'Expandir \u00C1rbol de Decisi\u00F3n',
ExplanationDectreetip:'Expande el \u00C1rbol de Decisi\u00F3n',
EditConstraintslabel:'Editar Restricciones en IDiagrams',
EditConstraintstip:'Edita las Restricciones en Diagramas de Influencia',
FileSaveAndReopenlabel:'Guardar y reabrir red',
EditContinuouslabel:'Inserta Nodo Continuo',
EditContinuoustip:'A\u00F1adir nodos continuos',
EditContinuousmnemonic:'T',
PopupExplainFunctionNodelabel:'Mostrar Funcion Detallada',
//#Introducido para el analisis de sensibilidad',
Analysislabel:'An\u00E1lisis',
Analysismnemonic:'A',
AnalysisSensitivityAnalysislabel:'An\u00E1lisis de sensibilidad',
AnalysisSensitivityAnalysismnemonic:'S',
AnalysisSensitivityAnalysistip:'An\u00E1lisis de sensibilidad',
SensitivityAnalysisOpciones:'Opciones',
SensitivityAnalysisCargarDiagrama:'Cargar diagrama',
SensitivityAnalysisGuardarDiagramaComo:'Guardar diagrama como ...',
SensitivityAnalysisGuardarDiagrama:'Guardar diagrama',
SensitivityAnalysisSalir:'Salir'
}
